# -*- coding: utf-8 -*-
"""homework1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wTsZVlFSLKVuxINjnOZBjxSZZaOQ3_S
"""

my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
# преобразуем нашу строку в список
fvr_songs_list = my_favorite_songs.split(', ')
print(fvr_songs_list)
# теперь можно вывести по одному
print(fvr_songs_list[0])
print(fvr_songs_list[-1])
print(fvr_songs_list[1])
print(fvr_songs_list[-2])